---
name: Report a bug
about: Something with znn_controller_dart is not working as expected
title: ''
labels: 'type:bug'
assignees: ''
---

#### System information

OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour


#### Actual behaviour


#### Steps to reproduce the behaviour


#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.